name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          command_timeout: 30m

          script: |

            cd /var/www/Maw-Buket

            echo "=== Pull Latest Code ==="
            git reset --hard
            git pull origin main

            echo "=== Laravel Maintenance Mode ==="
            php artisan down || true

            echo "=== Install Composer Dependencies ==="
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            echo "=== Install NPM Dependencies ==="
            npm install

            echo "=== Build Vite Assets ==="
            npm run build

            echo "=== Clear Laravel Cache ==="
            php artisan optimize:clear

            echo "=== Run Migration ==="
            php artisan migrate --force

            echo "=== Fix Permissions ==="
            chmod -R 775 storage bootstrap/cache

            echo "=== Rebuild Docker Images ==="
            docker compose build --no-cache

            echo "=== Redeploy Docker Swarm ==="
            docker stack deploy -c docker-compose.yml mawstack

            echo "=== Restart Laravel Containers ==="
            docker service update --force mawstack_app
            docker service update --force mawstack_nginx

            echo "=== Optimize Laravel ==="
            php artisan optimize

            echo "=== Laravel Up ==="
            php artisan up

            echo "=== Remove Old Docker Images ==="
            docker image prune -af

            echo "=== Deployment Finished ==="
